# Generated by Django 3.2.25 on 2024-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('complete', 'Complete'), ('pending', 'Pending')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('planning', 'Planning'), ('blocked', 'Blocked'), ('done', 'Done'), ('doing', 'Doing')], default='not started', max_length=255),
        ),
    ]
