# Generated by Django 3.2.25 on 2024-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241103_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('complete', 'Complete')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('blocked', 'Blocked'), ('done', 'Done'), ('doing', 'Doing'), ('not started', 'Not Started')], default='not started', max_length=255),
        ),
    ]
