# Generated by Django 3.2.25 on 2024-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
