# Generated by Django 3.2.25 on 2024-09-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
