# Generated by Django 3.2.25 on 2024-09-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='city',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zip',
        ),
    ]
