# Generated by Django 3.2.25 on 2024-10-28 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241028_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Enter phone number in the format '(123) 456-7890'.", max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number in the format '(123) 456-7890'.", regex='^\\(\\d{3}\\) \\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('pending', 'Pending'), ('complete', 'Complete')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('blocked', 'Blocked'), ('doing', 'Doing'), ('not started', 'Not Started'), ('planning', 'Planning')], default='not started', max_length=255),
        ),
    ]
