# Generated by Django 3.2.25 on 2024-09-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240911_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
