# Generated by Django 3.2.25 on 2024-10-28 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20241028_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('complete', 'Complete'), ('pending', 'Pending')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('doing', 'Doing'), ('blocked', 'Blocked'), ('planning', 'Planning'), ('not started', 'Not Started')], default='not started', max_length=255),
        ),
    ]
