# Generated by Django 3.2.25 on 2024-10-29 16:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241028_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_img',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('pending', 'Pending'), ('complete', 'Complete')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('doing', 'Doing'), ('done', 'Done'), ('planning', 'Planning'), ('blocked', 'Blocked')], default='not started', max_length=255),
        ),
    ]
