# Generated by Django 3.2.25 on 2024-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241029_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='2@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('blocked', 'Blocked'), ('doing', 'Doing'), ('not started', 'Not Started'), ('done', 'Done')], default='not started', max_length=255),
        ),
    ]
