# Generated by Django 3.2.25 on 2024-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20241029_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('complete', 'Complete')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('planning', 'Planning'), ('blocked', 'Blocked'), ('doing', 'Doing'), ('done', 'Done')], default='not started', max_length=255),
        ),
    ]
