# Generated by Django 3.2.25 on 2024-10-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20241029_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('complete', 'Complete'), ('pending', 'Pending')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Description of Task', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('done', 'Done'), ('doing', 'Doing'), ('planning', 'Planning'), ('not started', 'Not Started')], default='not started', max_length=255),
        ),
    ]
