# Generated by Django 3.2.25 on 2024-10-31 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20241029_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('pending', 'Pending'), ('complete', 'Complete')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('done', 'Done'), ('not started', 'Not Started'), ('doing', 'Doing'), ('planning', 'Planning')], default='not started', max_length=255),
        ),
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
