# Generated by Django 3.2.25 on 2024-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240913_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ein',
            field=models.CharField(max_length=10),
        ),
    ]
