# Generated by Django 3.2.25 on 2024-11-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20241102_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_sent',
            new_name='time_sent',
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('planned', 'Planned')], default='planned', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('done', 'Done'), ('doing', 'Doing'), ('planning', 'Planning'), ('not started', 'Not Started')], default='not started', max_length=255),
        ),
    ]
