# Generated by Django 3.2.25 on 2024-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_client_ein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_two',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
