# Generated by Django 3.2.25 on 2024-09-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client'),
            preserve_default=False,
        ),
    ]
