# Generated by Django 3.2.25 on 2024-09-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240915_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.project'),
            preserve_default=False,
        ),
    ]
