FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="christiangerard"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./run.sh /run.sh

ENV APP_HOST=app
ENV APP_PORT=9000

USER root

RUN mkdir -p /vol/static /var/www/certbot/.well-known/acme-challenge && \
    chmod 755 /vol/static /var/www/certbot && \
    touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf /var/www/certbot && \
    chmod +x /run.sh

VOLUME /vol/static
VOLUME /var/www/certbot

USER nginx

CMD ["/run.sh"]
