services:

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf  # Mount custom pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
      - certbot
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/vol/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/dns-route53
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ~/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: certonly --dns-route53 --force-renewal --email 1@christiangerard.me -d api.orka-app.com --agree-tos --noninteractive


  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}



volumes:
  postgres-data:
  static-data: